name: Deploy to Netlify

on:
  push:
    branches:
      - main # Replace 'main' with your default branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install

      - name: Build the site
        run: |
          npm run build  # Replace this with your build command if different

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2.4
        with:
          publish-dir: ./dist # Replace './dist' with your build output directory
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
