name: Deploy Angular App to Netlify

on:
  push:
    branches:
      - main # Replace 'main' with your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22" # Match the Node.js version your Angular project requires

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm ci

      # Step 4: Build the Angular application
      - name: Build Angular app
        run: |
          npm run build -- --output-path=dist

      # Step 5: Deploy to Netlify
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2.4
        with:
          publish-dir: dist # This is the default Angular build output directory
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
